### ISSUE TITLE
Override of boolean to false is ignored

### ISSUE THREAD

**Issue by maandr** [Typositoire/concourse-helm3-resource#30]
**Problem**
I have a boolean helm variable with a default value of true. I want to override this value on a specific environment to be false.

**Version**
1.9.2

**Description**
When defining an override for a boolean value as false then this override is not present as a --set parameter when helm is called.

**Example**
```
override_values:
  - key: global.isEnabled
     value: false
  - key: global.isDisabled
     value: true
```
Leads to a helm statement like this:
```
helm upgrade mychart ... --set global.isDisabled=true
```
I would expect:
```
helm upgrade mychart ... --set global.isEnabled=false --set global.isDisabled=true
```

**Comment by Typositoire** [comment]
Hum... No sure how to go about that... My guess is because ultimately it's yaml and `global.isDisabled` overwrites `global.isEnabled` since there's both under `global`.

Let me check some more so see what I can do.

**Comment by Typositoire** [comment]
So I just looked at some of our pipelines and we have pipelines with stuff like this:

```
override_values:
        - key: secrets.cc_password
          value: XXX
          hide: true
        - key: secrets.slack_url
          value: XXX
          hide: true
```

I'll test with 1.9.2 it could be a regression.
