### ISSUE TITLE
Allow specifying unencoded cluster CA certficate

### ISSUE THREAD

**Issue by vixus0** [Typositoire/concourse-helm3-resource#39]
When running Concourse configured with the Kubernetes secret credential source, I can use the secret that gets dynamically generated for each cluster `ServiceAccount` to authenticate this resource to the cluster. The dynamic secret conveniently provides the token and CA certificate required by the resource and is easy to access with Concourse. For example, I should be able to do:

```yaml
resources:
  - name: helm-release
    type: helm
    source:
      namespace: ((concourse-deployer-token.namespace))
      cluster_url: "https://kubernetes.default.svc"
      cluster_ca: ((concourse-deployer-token."ca.crt"))
      token: ((concourse-deployer-token.token))
```

However this currently isn't possible because the resource expects a Base64-encoded certificate, and `((concourse-deployer-token."ca.crt"))` evaluates to the unencoded PEM.

Maybe we could have a new parameter like `cluster_ca_pem` that accepts the unencoded PEM? I'm happy to raise a PR to implement this if it seems suitable.
