### ISSUE TITLE
Check step fails when using kubeconfig_path param 

### ISSUE THREAD

**Issue by will-gant** [Typositoire/concourse-helm3-resource#43]
Hi there

I've run into an issue when my resource is defined without a URL/creds for my k8s cluster, which are instead provided via the `kubeconfig_path` param on a put as follows:

```
resources:
- name: minibroker
  type: helm
  source:
    release: minibroker
    repos:
      - name: minibroker
        url: https://minibroker.blob.core.windows.net/charts

...
jobs:
 - put: minibroker
    params:
      chart: minibroker/minibroker
      kubeconfig_path: kubeconfig/kubeconfig.yaml
```

With this configuration my `put` succeeds but then the resource box leaving my job shows up orange in the Concourse UI, as the resource check errors as follows:

![image](https://user-images.githubusercontent.com/20523607/101894712-de974e80-3ba6-11eb-916e-27937959ab4e.png)
![image](https://user-images.githubusercontent.com/20523607/101894695-d8a16d80-3ba6-11eb-96ed-891a1c368b4c.png)

I might not have quite understood how I should configure the resource, but perhaps the issue I'm hitting is that the function setup_kubernetes [always exits 1 if neither a cluster URL nor kubeconfig are defined in the resource's source block].

In our case we particularly want to provide a kubeconfig file as a `put` param because we construct that file earlier in the same pipeline job from terraform outputs.

**Comment by Typositoire** [comment]
Have you tried setting `get_params: { kubeconfig_path: kubeconfig/kubeconfig.yaml }`  I think it might work. It's because the `check` doesn't use the path in your `put params` well... because it's the `check` :p Give this a whirl and let me know.

**Comment by will-gant** [comment]
Hey

Unfortunately that doesn't fix the issue. I've done as you suggest, and now my `put` looks like this:

```
- put: minibroker
  params:
    chart: minibroker/minibroker
    kubeconfig_path: kubeconfig/kubeconfig.yaml
  get_params:
    kubeconfig_path: kubeconfig/kubeconfig.yaml
```

The implicit `get` after the `put` does indeed succeed (although it did already before this change). Checks continue to fail with the same error as previously:

```
run check step: run check step: check: resource script '/opt/resource/check []' failed: exit status 1

stderr:
Initializing kubectl...
invalid payload (missing cluster_url)
```
