### ISSUE TITLE
Error: unknown command "diff" for "helm"

### ISSUE THREAD

**Issue by luceos** [Typositoire/concourse-helm3-resource#77]
Been running into this issue for a few days, not sure what is happening.

- helm 3.8.0
- go 1.17.5

**resource_type**

```yml
  -
    name: helm
    type: docker-image
    source:
      repository: ghcr.io/typositoire/concourse-helm3-resource
      tag: v1.19.1
```

**resource**

```yml
 -
    name: some-helm-repo
    type: helm
    check_every: 10s
    source:
      cluster_url: ((common-secrets.k8s_frankfurt_control_plane))
      cluster_ca: ((common-secrets.k8s_frankfurt_cad))
      token: ((common-secrets.k8s_frankfurt_token))
      repos:
        -
          name: company
          url: 'https://helm.repo/chartrepo/library'
          username: ((common-secrets.harbor_username))
          password: ((common-secrets.harbor_password))
        -
          name: bitnami
          url: 'https://charts.bitnami.com/bitnami'
```

**task**

```yml

      - put: some-helm-repo
        params:
          chart: bitnami/redis
          values: community-helm-values-bucket-redis/redis.yml
          version: 14.4.0
          atomic: true
          namespace: x61e3ff9f
          timeout: 3m0s
          show_diff: true
          release: redis
```

Output in concourse:

```
Resource setup successful.

Installing redis

Release diff:

Error: unknown command "diff" for "helm"
Run 'helm --help' for usage.
```

So far I tried:

- resource type without tag (original state)
- using resource type with tag v1.20.0
- using resource type with tag v1.19.1

Somehow I feel this is an issue higher up, but I can't really pin it. Advice would really be great 🙏
