### ISSUE TITLE
Error when specifiying version

### ISSUE THREAD

**Issue by lareeth** [Typositoire/concourse-helm3-resource#9]
When adding version to params, concourse fails the build with the following error

```
invalid payload (missing version if chart is from repository.
```

https://github.com/Typositoire/concourse-helm3-resource/blob/fd6d248676d72d08655c63d0025de3b3e704349a/assets/out#L62-L64

Should this be using `-n` and not `-z` to check if its empty, instead of checking that its got a value.

This is the job i have  added it to, when removing the version it installs fine. However I want to explicitly set the version for each chart.

```
- name: external-dns
  plan:
  - get: helm-config
  - put: helm-external-dns
    params:
      chart: stable/external-dns
      values: helm-config/helm/engineering/external-dns.yml
      version: 2.14.3
```
